FIND_PATH(MYNT_INCLUDE_DIR mynteye/mynteye.h)
FIND_LIBRARY(MYNT_LIBRARY mynteye_core)

SET(MYNTEYESDK_FOUND "NO")
IF(MYNT_INCLUDE_DIR AND MYNT_LIBRARY)
  SET(MYNTEYESDK_FOUND "YES")
ENDIF(MYNT_INCLUDE_DIR AND MYNT_LIBRARY)

